#SYSTEM
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_MAIN_STACK_SIZE=2048

#PERIPHERALS
# CONFIG_ADC=y
# CONFIG_ADC_LOG_LEVEL_DBG=y
# CONFIG_I2C=y
# CONFIG_SENSOR=y
# CONFIG_BME280=y

#BLUETOOTH
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_DEVICE_NAME="NRF5340Dev"
CONFIG_BT_GATT_CACHING=y
CONFIG_BT_GATT_SERVICE_CHANGED=y

